language: node_js

node_js:
  - 'stable'
  - 'lts/*'

sudo: false

env:
  global:
    - CC_TEST_REPORTER_ID=8f0bca23bd4a9d1712ffe06e1315a8c903f7874ae6ff831efab7ab6d530e0a2e
  - workerCount=3

matrix:
  fast_finish: true

branches:
  only:
  - master
  - dev

install:
  - npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - rollup -c
  - npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  directories:
    - node_modules
    - .rpt2_cache

git:
  depth: 3
